language: ruby

rvm:
 - "2.2.2"

services:
 - postgresql

before_script:
  - cp config/database.yml.travis config/database.yml
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - rackup  # start a Web server
  - sleep 3 # give Web server some time to bind to sockets, etc

script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake db:seed
  - bundle exec rake

addons:
  sauce_connect:
    username: "deannawarren"
    access_key: "9db15b18-d6d1-4d91-9f7b-15806fed6437"


